-- 코드를 입력하세요
SELECT
FROM USED_GOODS_BOARD AS B
JOIN USED_GOODS_REPLY AS R ON B.BOARD_ID = R.BOARD_ID
WHERE B.CREATED_DATE IN (SELECT CREATED_DATE
                         FROM USED_GOODS_BOARD
                         )