SELECT BOARD.TITLE, REPLY.BOARD_ID, REPLY.REPLY_ID, REPLY.WRITER_ID, REPLY.CONTENTS, DATE_FORMAT(REPLY.CREATED_DATE, '%Y-%m-%d') "CREATED_DATE"
FROM USED_GOODS_REPLY as REPLY
JOIN USED_GOODS_BOARD as BOARD
USING(BOARD_ID)
WHERE MONTH(BOARD.CREATED_DATE) = '10'
ORDER BY REPLY.CREATED_DATE, BOARD.TITLE
